# Generated by Django 6.0 on 2026-04-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_supplementary',
        ),
        migrations.AddField(
            model_name='examresult',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='student_audio/%Y/%m/', verbose_name='File ghi âm MP3'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='cheating_flag',
            field=models.BooleanField(default=False, verbose_name='Cảnh báo gian lận'),
        ),
        migrations.CreateModel(
            name='ViolationImage',
            fields=[
                ('violation_image_id', models.AutoField(db_column='violation_image_id', primary_key=True, serialize=False)),
                ('image_blob', models.BinaryField(verbose_name='Ảnh gian lận')),
                ('image_mime', models.CharField(default='image/jpeg', max_length=100, verbose_name='MIME type ảnh')),
                ('violation_type', models.CharField(default='TWO_FACES', max_length=50, verbose_name='Loại gian lận')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm ghi nhận')),
                ('exam_session_id', models.ForeignKey(db_column='exam_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='violation_images', to='qna.examsession', verbose_name='Phiên thi')),
            ],
            options={
                'verbose_name': 'Hình ảnh gian lận',
                'verbose_name_plural': 'Hình ảnh gian lận',
                'db_table': 'violation_image',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SupplementaryResult',
        ),
    ]
