# Generated by Django 6.0 on 2026-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_remove_question_is_supplementary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu làm bài'),
        ),
    ]
