# Generated by Django 6.0.4 on 2026-04-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_examset_exam_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects_enrolled',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='qna.subject'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='student_audio/%Y/%m/', verbose_name='File ghi âm'),
        ),
    ]
