# Generated by Django 6.0 on 2026-04-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_examsession_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAppeal',
            fields=[
                ('exam_appeal_id', models.AutoField(db_column='exam_appeal_id', primary_key=True, serialize=False)),
                ('request_content', models.TextField(verbose_name='Nội dung phúc khảo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('exam_session_id', models.OneToOneField(db_column='exam_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='qna.examsession', verbose_name='Phiên thi')),
            ],
            options={
                'verbose_name': 'Yêu cầu phúc khảo',
                'verbose_name_plural': 'Yêu cầu phúc khảo',
                'db_table': 'exam_appeal',
            },
        ),
    ]
