# Generated by Django 6.0.4 on 2026-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_examappeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='examsession',
            name='session_status',
            field=models.CharField(choices=[('PENDING', 'Chờ'), ('STARTED', 'Đã bắt đầu'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái phiên thi'),
        ),
    ]
