# Generated by Django 6.0 on 2026-04-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_userprofile_subjects_enrolled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at', 'question_id'], 'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Câu hỏi'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_id_in_barem',
        ),
    ]
