# Generated by Django 6.0 on 2026-04-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examset',
            name='easy_pool_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Số câu dễ trong ma trận'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='easy_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm câu dễ'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='hard_pool_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Số câu khó trong ma trận'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='hard_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm câu khó'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='medium_pool_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Số câu trung bình trong ma trận'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='medium_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Điểm câu trung bình'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='number_of_versions',
            field=models.PositiveIntegerField(default=0, verbose_name='Số mã đề'),
        ),
    ]
