# Generated by Django 6.0 on 2026-04-10 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_remove_examsession_is_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examappeal',
            options={'verbose_name': 'YÃªu cáº§u phÃºc kháº£o', 'verbose_name_plural': 'YÃªu cáº§u phÃºc kháº£o'},
        ),
        migrations.AlterModelOptions(
            name='examcode',
            options={'ordering': ['code_number', 'created_at'], 'verbose_name': 'MÃ£ Ä‘á»\x81 thi', 'verbose_name_plural': 'MÃ£ Ä‘á»\x81 thi'},
        ),
        migrations.AlterModelOptions(
            name='examcodequestion',
            options={'ordering': ['display_order', 'exam_code_question_id'], 'verbose_name': 'CÃ¢u há»\x8fi trong mÃ£ Ä‘á»\x81', 'verbose_name_plural': 'CÃ¢u há»\x8fi trong mÃ£ Ä‘á»\x81'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Káº¿t quáº£ thi', 'verbose_name_plural': 'Káº¿t quáº£ thi'},
        ),
        migrations.AlterModelOptions(
            name='examroom',
            options={'ordering': ['room_code'], 'verbose_name': 'PhÃ²ng thi', 'verbose_name_plural': 'PhÃ²ng thi'},
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={'verbose_name': 'PhiÃªn thi', 'verbose_name_plural': 'PhiÃªn thi'},
        ),
        migrations.AlterModelOptions(
            name='examsessionroom',
            options={'ordering': ['display_order', 'exam_session_room_id'], 'verbose_name': 'PhÃ²ng thi trong ca thi', 'verbose_name_plural': 'PhÃ²ng thi trong ca thi'},
        ),
        migrations.AlterModelOptions(
            name='examset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bá»™ Ä‘á»\x81 thi', 'verbose_name_plural': 'Bá»™ Ä‘á»\x81 thi'},
        ),
        migrations.AlterModelOptions(
            name='lecturematerial',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'TÃ\xa0i liá»‡u bÃ\xa0i giáº£ng', 'verbose_name_plural': 'TÃ\xa0i liá»‡u bÃ\xa0i giáº£ng'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_id_in_barem', 'question_id'], 'verbose_name': 'CÃ¢u há»\x8fi', 'verbose_name_plural': 'CÃ¢u há»\x8fi'},
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={'ordering': ['-created_at'], 'verbose_name': 'NgÃ¢n hÃ\xa0ng cÃ¢u há»\x8fi', 'verbose_name_plural': 'NgÃ¢n hÃ\xa0ng cÃ¢u há»\x8fi'},
        ),
        migrations.AlterModelOptions(
            name='studentrosterstudent',
            options={'ordering': ['row_number', 'student_roster_student_id'], 'verbose_name': 'Sinh viÃªn trong danh sÃ¡ch', 'verbose_name_plural': 'Sinh viÃªn trong danh sÃ¡ch'},
        ),
        migrations.AlterModelOptions(
            name='studentrosterupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Danh sÃ¡ch lá»›p táº£i lÃªn', 'verbose_name_plural': 'Danh sÃ¡ch lá»›p táº£i lÃªn'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'MÃ´n há»\x8dc', 'verbose_name_plural': 'MÃ´n há»\x8dc'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Há»“ sÆ¡ ngÆ°á»\x9di dÃ¹ng', 'verbose_name_plural': 'Há»“ sÆ¡ ngÆ°á»\x9di dÃ¹ng'},
        ),
        migrations.AlterModelOptions(
            name='violationimage',
            options={'ordering': ['-timestamp'], 'verbose_name': 'HÃ¬nh áº£nh gian láº\xadn', 'verbose_name_plural': 'HÃ¬nh áº£nh gian láº\xadn'},
        ),
        migrations.AlterField(
            model_name='examappeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='examappeal',
            name='exam_session_id',
            field=models.OneToOneField(db_column='exam_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='qna.examsession', verbose_name='PhiÃªn thi'),
        ),
        migrations.AlterField(
            model_name='examappeal',
            name='request_content',
            field=models.TextField(verbose_name='Ná»™i dung phÃºc kháº£o'),
        ),
        migrations.AlterField(
            model_name='examappeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='NgÃ\xa0y cáº\xadp nháº\xadt'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='code_name',
            field=models.CharField(max_length=100, verbose_name='TÃªn mÃ£ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='code_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Sá»‘ thá»© tá»± mÃ£ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='exam_set_id',
            field=models.ForeignKey(blank=True, db_column='exam_set_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_codes', to='qna.examset', verbose_name='Bá»™ Ä‘á»\x81 thi'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Ä\x90Ã£ duyá»‡t'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='source_material',
            field=models.TextField(blank=True, null=True, verbose_name='Nguá»“n tÃ\xa0i liá»‡u'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_codes', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='examcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='NgÃ\xa0y cáº\xadp nháº\xadt'),
        ),
        migrations.AlterField(
            model_name='examcodequestion',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Dá»…'), ('MEDIUM', 'Trung bÃ¬nh'), ('HARD', 'KhÃ³')], max_length=10, verbose_name='Ä\x90á»™ khÃ³'),
        ),
        migrations.AlterField(
            model_name='examcodequestion',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Thá»© tá»± hiá»ƒn thá»‹'),
        ),
        migrations.AlterField(
            model_name='examcodequestion',
            name='exam_code_id',
            field=models.ForeignKey(db_column='exam_code_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_code_questions', to='qna.examcode', verbose_name='MÃ£ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='examcodequestion',
            name='question_id',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_code_items', to='qna.question', verbose_name='CÃ¢u há»\x8fi'),
        ),
        migrations.AlterField(
            model_name='examcodequestion',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Ä\x90iá»ƒm'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='PhÃ¢n tÃ\xadch chi tiáº¿t'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='student_audio/%Y/%m/', verbose_name='File ghi Ã¢m MP3'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Nháº\xadn xÃ©t cá»§a AI'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='score',
            field=models.FloatField(verbose_name='Ä\x90iá»ƒm sá»‘'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='transcript',
            field=models.TextField(verbose_name='Ná»™i dung tráº£ lá»\x9di'),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Sá»©c chá»©a'),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='room_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='MÃ£ phÃ²ng'),
        ),
        migrations.AlterField(
            model_name='examroom',
            name='room_name',
            field=models.CharField(max_length=100, verbose_name='TÃªn phÃ²ng'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='cheating_flag',
            field=models.BooleanField(default=False, verbose_name='Cáº£nh bÃ¡o gian láº\xadn'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thá»\x9di gian hoÃ\xa0n thÃ\xa0nh'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y thi'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='face_image_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='áº¢nh khuÃ´n máº·t chá»¥p tá»« webcam'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='face_image_mime',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type áº£nh khuÃ´n máº·t'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='id_card_image_blob',
            field=models.BinaryField(blank=True, null=True, verbose_name='áº¢nh tháº» sinh viÃªn'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='id_card_image_mime',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='MIME type áº£nh tháº»'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='needs_manual_review',
            field=models.BooleanField(default=False, verbose_name='Cáº§n kiá»ƒm tra thá»§ cÃ´ng'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='session_status',
            field=models.CharField(choices=[('PENDING', 'Chá»\x9d'), ('STARTED', 'Ä\x90Ã£ báº¯t Ä‘áº§u'), ('COMPLETED', 'HoÃ\xa0n thÃ\xa0nh'), ('CANCELLED', 'Há»§y')], default='PENDING', max_length=20, verbose_name='Tráº¡ng thÃ¡i phiÃªn thi'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thá»\x9di gian báº¯t Ä‘áº§u lÃ\xa0m bÃ\xa0i'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='verification_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Ä\x90iá»ƒm tÆ°Æ¡ng Ä‘á»“ng (0-1)'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Chá»\x9d xÃ¡c thá»±c'), ('ALLOW', 'Cho phÃ©p thi'), ('WARNING_ALLOW', 'Cho phÃ©p thi (cáº§n kiá»ƒm tra láº¡i)'), ('BLOCK', 'Cháº·n thi')], default='PENDING', max_length=20, verbose_name='Tráº¡ng thÃ¡i xÃ¡c thá»±c'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='NÄƒm há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='configuration_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cáº¥u hÃ¬nh ca thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='created_by_user_id',
            field=models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='created_exam_groups', to=settings.AUTH_USER_MODEL, verbose_name='NgÆ°á»\x9di táº¡o'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='MÃ´ táº£ ká»³ thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Thá»\x9di gian lÃ\xa0m bÃ\xa0i (phÃºt)'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='exam_codes',
            field=models.ManyToManyField(related_name='exam_session_groups', to='qna.examcode', verbose_name='MÃ£ Ä‘á»\x81 thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='exam_date',
            field=models.DateTimeField(verbose_name='NgÃ\xa0y giá»\x9d thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='exam_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Máº\xadt kháº©u bÃ\xa0i thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='group_name',
            field=models.CharField(max_length=200, verbose_name='TÃªn ca thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='rooms',
            field=models.ManyToManyField(through='qna.ExamSessionRoom', to='qna.examroom', verbose_name='PhÃ²ng thi'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='semester',
            field=models.CharField(choices=[('HK1', 'Há»\x8dc ká»³ 1'), ('HK2', 'Há»\x8dc ká»³ 2'), ('SUMMER', 'Há»\x8dc ká»³ hÃ¨')], default='HK1', max_length=10, verbose_name='Há»\x8dc ká»³'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'NhÃ¡p'), ('SCHEDULED', 'Ä\x90Ã£ lÃªn lá»‹ch'), ('ONGOING', 'Ä\x90ang diá»…n ra'), ('COMPLETED', 'Ä\x90Ã£ káº¿t thÃºc'), ('CANCELLED', 'Ä\x90Ã£ há»§y')], default='DRAFT', max_length=20, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_session_groups', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='examsessiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='NgÃ\xa0y cáº\xadp nháº\xadt'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='display_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Thá»© tá»± hiá»ƒn thá»‹'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='exam_codes',
            field=models.ManyToManyField(blank=True, related_name='session_rooms', to='qna.examcode', verbose_name='MÃ£ Ä‘á»\x81 gáº¯n cho phÃ²ng'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='exam_set_id',
            field=models.ForeignKey(blank=True, db_column='exam_set_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_rooms', to='qna.examset', verbose_name='Bá»™ Ä‘á»\x81 gáº¯n cho phÃ²ng'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='expected_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Sá»‘ lÆ°á»£ng sinh viÃªn dá»± kiáº¿n'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='room_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='TÃªn phÃ²ng hiá»ƒn thá»‹'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='room_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Máº\xadt kháº©u phÃ²ng'),
        ),
        migrations.AlterField(
            model_name='examsessionroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='exam_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viÃªn'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='NÄƒm há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='allow_duplicate_questions',
            field=models.BooleanField(default=False, verbose_name='Cho phÃ©p cÃ¢u há»\x8fi trÃ¹ng láº·p giá»¯a cÃ¡c mÃ£ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_sets', to=settings.AUTH_USER_MODEL, verbose_name='NgÆ°á»\x9di táº¡o'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='easy_pool_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Sá»‘ cÃ¢u dá»… trong ma tráº\xadn'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='easy_score',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=5, verbose_name='Ä\x90iá»ƒm cÃ¢u dá»…'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='hard_pool_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Sá»‘ cÃ¢u khÃ³ trong ma tráº\xadn'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='hard_score',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=5, verbose_name='Ä\x90iá»ƒm cÃ¢u khÃ³'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='medium_pool_size',
            field=models.PositiveIntegerField(default=1, verbose_name='Sá»‘ cÃ¢u trung bÃ¬nh trong ma tráº\xadn'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='medium_score',
            field=models.DecimalField(decimal_places=1, default=2.5, max_digits=5, verbose_name='Ä\x90iá»ƒm cÃ¢u trung bÃ¬nh'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='TÃªn bá»™ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='number_of_versions',
            field=models.PositiveIntegerField(default=1, verbose_name='Sá»‘ mÃ£ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='question_banks',
            field=models.ManyToManyField(blank=True, related_name='exam_sets', to='qna.questionbank', verbose_name='Nguá»“n cÃ¢u há»\x8fi'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='semester',
            field=models.CharField(choices=[('HK1', 'Há»\x8dc ká»³ 1'), ('HK2', 'Há»\x8dc ká»³ 2'), ('SUMMER', 'Há»\x8dc ká»³ hÃ¨')], default='HK1', max_length=10, verbose_name='Há»\x8dc ká»³'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='shuffle_question_order',
            field=models.BooleanField(default=True, verbose_name='Tá»± Ä‘á»™ng xÃ¡o trá»™n thá»© tá»± cÃ¢u há»\x8fi'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ChÆ°a duyá»‡t'), ('APPROVED', 'Ä\x90Ã£ duyá»‡t')], default='DRAFT', max_length=20, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='exam_sets', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='examset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='NgÃ\xa0y cáº\xadp nháº\xadt'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='Ä\x90Æ°á»\x9dng dáº«n file'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='file_type',
            field=models.CharField(max_length=50, verbose_name='Loáº¡i file'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='question_bank_id',
            field=models.ForeignKey(blank=True, db_column='question_bank_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='qna.questionbank', verbose_name='NgÃ¢n hÃ\xa0ng cÃ¢u há»\x8fi'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='lecture_materials', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='title',
            field=models.CharField(max_length=255, verbose_name='TiÃªu Ä‘á»\x81 tÃ\xa0i liá»‡u'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y upload'),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='workspace_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phi lÃ\xa0m viá»‡c'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Dá»…'), ('MEDIUM', 'Trung bÃ¬nh'), ('HARD', 'KhÃ³')], default='EASY', max_length=10, verbose_name='Ä\x90á»™ khÃ³'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Báº£n nhÃ¡p chÆ°a lÆ°u'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_exam_clone',
            field=models.BooleanField(default=False, verbose_name='Báº£n sao dÃ¹ng cho mÃ£ Ä‘á»\x81'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_bank_id',
            field=models.ForeignKey(blank=True, db_column='question_bank_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qna.questionbank', verbose_name='NgÃ¢n hÃ\xa0ng cÃ¢u há»\x8fi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id_in_barem',
            field=models.CharField(help_text='VÃ\xad dá»¥: Q1, Q2...', max_length=50, verbose_name='ID cÃ¢u há»\x8fi trong tá»‡p barem'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Ná»™i dung cÃ¢u há»\x8fi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text_normalized',
            field=models.TextField(blank=True, null=True, verbose_name='CÃ¢u há»\x8fi chuáº©n hÃ³a'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='name',
            field=models.CharField(max_length=255, verbose_name='TÃªn ngÃ¢n hÃ\xa0ng'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='account_created',
            field=models.BooleanField(default=False, verbose_name='Ä\x90Ã£ cÃ³ tÃ\xa0i khoáº£n'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'ChÆ°a cÃ³'), ('EXISTING', 'Ä\x90Ã£ cÃ³ sáºµn'), ('CREATED', 'Má»›i táº¡o')], default='PENDING', max_length=20, verbose_name='Nguá»“n tráº¡ng thÃ¡i tÃ\xa0i khoáº£n'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lá»›p'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº¡o'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='NgÃ\xa0y sinh'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Há»\x8d vÃ\xa0 tÃªn'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Giá»›i tÃ\xadnh'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='linked_user_id',
            field=models.ForeignKey(blank=True, db_column='linked_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_list_rows', to=settings.AUTH_USER_MODEL, verbose_name='TÃ\xa0i khoáº£n liÃªn káº¿t'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='student_code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='MÃ£ sá»‘ sinh viÃªn'),
        ),
        migrations.AlterField(
            model_name='studentrosterstudent',
            name='student_roster_upload_id',
            field=models.ForeignKey(db_column='student_roster_upload_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='qna.studentrosterupload', verbose_name='Tá»‡p danh sÃ¡ch'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='academic_year',
            field=models.CharField(max_length=20, verbose_name='NÄƒm há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='account_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='NgÃ\xa0y táº¡o tÃ\xa0i khoáº£n'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='NgÃ\xa0y táº£i lÃªn'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_roster_uploads', to=settings.AUTH_USER_MODEL, verbose_name='NgÆ°á»\x9di táº£i lÃªn'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='original_file_name',
            field=models.CharField(max_length=255, verbose_name='TÃªn file gá»‘c'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='semester',
            field=models.CharField(choices=[('HK1', 'Há»\x8dc ká»³ 1'), ('HK2', 'Há»\x8dc ká»³ 2'), ('SUMMER', 'Há»\x8dc ká»³ hÃ¨')], default='HK1', max_length=10, verbose_name='Há»\x8dc ká»³'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ChÆ°a táº¡o'), ('CREATED', 'Ä\x90Ã£ táº¡o')], default='PENDING', max_length=20, verbose_name='Tráº¡ng thÃ¡i'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='subject_id',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='student_roster_uploads', to='qna.subject', verbose_name='MÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='title',
            field=models.CharField(max_length=255, verbose_name='TÃªn hiá»ƒn thá»‹'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='total_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Sá»‘ lÆ°á»£ng sinh viÃªn'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='NgÃ\xa0y cáº\xadp nháº\xadt'),
        ),
        migrations.AlterField(
            model_name='studentrosterupload',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='student_lists/%Y/%m/', verbose_name='Tá»‡p danh sÃ¡ch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_password',
            field=models.CharField(blank=True, help_text='Máº\xadt kháº©u Ä‘á»ƒ sinh viÃªn vÃ\xa0o bÃ\xa0i thi (Ä‘á»ƒ trá»‘ng náº¿u khÃ´ng cáº§n)', max_length=100, null=True, verbose_name='Máº\xadt kháº©u bÃ\xa0i thi'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='TÃªn mÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='quiz_data_file',
            field=models.CharField(blank=True, help_text='VÃ\xad dá»¥: data_analysis_quiz.json', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='MÃ£ mÃ´n há»\x8dc'),
        ),
        migrations.AlterField(
            model_name='violationimage',
            name='exam_session_id',
            field=models.ForeignKey(db_column='exam_session_id', on_delete=django.db.models.deletion.CASCADE, related_name='violation_images', to='qna.examsession', verbose_name='PhiÃªn thi'),
        ),
        migrations.AlterField(
            model_name='violationimage',
            name='image_blob',
            field=models.BinaryField(verbose_name='áº¢nh gian láº\xadn'),
        ),
        migrations.AlterField(
            model_name='violationimage',
            name='image_mime',
            field=models.CharField(default='image/jpeg', max_length=100, verbose_name='MIME type áº£nh'),
        ),
        migrations.AlterField(
            model_name='violationimage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thá»\x9di Ä‘iá»ƒm ghi nháº\xadn'),
        ),
        migrations.AlterField(
            model_name='violationimage',
            name='violation_type',
            field=models.CharField(default='TWO_FACES', max_length=50, verbose_name='Loáº¡i gian láº\xadn'),
        ),
    ]
