# Generated by Django 6.0 on 2026-04-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_alter_examset_easy_pool_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examset',
            name='shuffle_question_order',
        ),
    ]
