# Generated by Django 6.0.4 on 2026-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_alter_examappeal_options_alter_examcode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationimage',
            name='image_blob',
        ),
        migrations.AddField(
            model_name='violationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='violations/', verbose_name='áº¢nh gian láº\xadn'),
        ),
    ]
