# Generated by Django 6.0 on 2026-03-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0014_alter_question_options_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerial',
            name='workspace_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phiên làm việc'),
        ),
    ]
