# Generated by Django 6.0 on 2026-03-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0015_lecturematerial_workspace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên ngân hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='qna.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Ngân hàng câu hỏi',
                'verbose_name_plural': 'Ngân hàng câu hỏi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lecturematerial',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='qna.questionbank', verbose_name='Ngân hàng câu hỏi'),
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qna.questionbank', verbose_name='Ngân hàng câu hỏi'),
        ),
    ]
