# Generated by Django 6.0 on 2026-03-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0017_examset_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcode',
            options={'ordering': ['code_number', 'created_at'], 'verbose_name': 'Mã đề thi', 'verbose_name_plural': 'Mã đề thi'},
        ),
    ]
