# Generated by Django 6.0 on 2026-03-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0018_alter_examcode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcode',
            name='question_easy',
        ),
        migrations.RemoveField(
            model_name='examcode',
            name='question_hard',
        ),
        migrations.RemoveField(
            model_name='examcode',
            name='question_medium',
        ),
        migrations.RemoveField(
            model_name='examcode',
            name='question_order',
        ),
        migrations.CreateModel(
            name='ExamCodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', 'Dễ'), ('MEDIUM', 'Trung bình'), ('HARD', 'Khó')], max_length=10, verbose_name='Độ khó')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='Thứ tự hiển thị')),
                ('score', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Điểm')),
                ('exam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_code_questions', to='qna.examcode', verbose_name='Mã đề')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_code_items', to='qna.question', verbose_name='Câu hỏi')),
            ],
            options={
                'verbose_name': 'Câu hỏi trong mã đề',
                'verbose_name_plural': 'Câu hỏi trong mã đề',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
