# Generated by Django 6.0 on 2026-03-18 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0019_remove_examcode_question_easy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRosterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Năm học')),
                ('semester', models.CharField(choices=[('HK1', 'Học kỳ 1'), ('HK2', 'Học kỳ 2'), ('SUMMER', 'Học kỳ hè')], default='HK1', max_length=10, verbose_name='Học kỳ')),
                ('title', models.CharField(max_length=255, verbose_name='Tên hiển thị')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='Tên file gốc')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='student_lists/%Y/%m/', verbose_name='Tệp danh sách')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Số lượng sinh viên')),
                ('status', models.CharField(choices=[('PENDING', 'Chưa tạo'), ('CREATED', 'Đã tạo')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('account_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày tạo tài khoản')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_roster_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roster_uploads', to='qna.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Danh sách lớp tải lên',
                'verbose_name_plural': 'Danh sách lớp tải lên',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRosterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=1, verbose_name='STT')),
                ('student_code', models.CharField(db_index=True, max_length=50, verbose_name='Mã số sinh viên')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('gender', models.CharField(blank=True, default='', max_length=20, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('class_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Lớp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('account_created', models.BooleanField(default=False, verbose_name='Đã có tài khoản')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_list_rows', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản liên kết')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='qna.studentrosterupload', verbose_name='Tệp danh sách')),
            ],
            options={
                'verbose_name': 'Sinh viên trong danh sách',
                'verbose_name_plural': 'Sinh viên trong danh sách',
                'ordering': ['row_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('roster', 'student_code'), name='unique_student_code_per_roster')],
            },
        ),
    ]
